name: Deploy Frontend to Kubernetes

on:
  push:
    branches:
        - main  # Production branch
        - staging  # Staging branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/frontend:latest .

    - name: Push Docker image
      run: |
        docker push your-dockerhub-username/frontend:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Configure Kubernetes credentials
      run: echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig && export KUBECONFIG=kubeconfig

    - name: Deploy frontend to Kubernetes
      run: |
        kubectl set image deployment/frontend your-frontend-deployment=your-dockerhub-username/frontend:latest
        kubectl rollout status deployment/frontend
