export const investmentRow = [
  {
    id: 1,
    dateCreated: "May 1, 2023, 9:00AM",
    propertyInvested: "Bradford Apartment",
    customer: "Owolu Opeyemi",
    amount: "28,000,000.00",
    investmentType: "Property Purchase",
  },
  {
    id: 2,
    dateCreated: "May 1, 2023, 9:00AM",
    propertyInvested: "Leeds II Apartment",
    customer: "Victor Tosin",
    amount: "4,000,000.00",
    investmentType: "Co-ownership",
  },
  {
    id: 2,
    dateCreated: "May 1, 2023, 9:00AM",
    propertyInvested: "Prime Apartment",
    customer: "Azeez Kiki",
    amount: "500,000.00",
    investmentType: "Co-ownership",
  },
  {
    id: 2,
    dateCreated: "May 1, 2023, 9:00AM",
    propertyInvested: "Bradford Suites",
    customer: "Azeez Kiki",
    amount: "2,500,000.00",
    investmentType: "Property Purchase",
  },
  {
    id: 2,
    dateCreated: "May 1, 2023, 9:00AM",
    propertyInvested: "Bradford Suites",
    customer: "Azeez Kiki",
    amount: "200,000.00",
    investmentType: "Property Purchase",
  },
  {
    id: 2,
    dateCreated: "May 1, 2023, 9:00AM",
    propertyInvested: "Bradford Suites",
    customer: "Azeez Kiki",
    amount: "500,000.00",
    investmentType: "Property Purchase",
  },
  {
    id: 2,
    dateCreated: "May 1, 2023, 9:00AM",
    propertyInvested: "Bradford Suites",
    customer: "Azeez Kiki",
    amount: "10,000,000.00",
    investmentType: "Co-ownership",
  },
  {
    id: 2,
    dateCreated: "May 1, 2023, 9:00AM",
    propertyInvested: "Bradford Suites",
    customer: "Azeez Kiki",
    amount: "10,000,000.00",
    investmentType: "Co-ownership",
  },
  {
    id: 2,
    dateCreated: "May 1, 2023, 9:00AM",
    propertyInvested: "Bradford Suites",
    customer: "Azeez Kiki",
    amount: "500,000.70",
    investmentType: "Co-ownership",
  },
];
