import { propertyRows } from "../types";

export const rows: propertyRows[] = [
  {
    id: 1,
    dateAdded: "May 1, 2023",
    propertyName: "Bradford Apartment",
    address: "32, Herbert, Yaba, Lagos",
    unitsLeft: "23",
    propertyType: "Property Purchase",
    status: "Still Selling",
  },
  {
    id: 2,
    dateAdded: "May 1, 2023",
    propertyName: "Leeds 2 Apartment",
    address: "32, Herbert, Yaba, Lagos",
    unitsLeft: "0",
    propertyType: "Co-ownership",
    status: "Sold Out",
  },
  {
    id: 3,
    dateAdded: "May 1, 2023",
    propertyName: "Leeds 1 Apartment",
    address: "32, Herbert, Yaba, Lagos",
    unitsLeft: "13",
    propertyType: "Property Purchase",
    status: "Still Selling",
  },
  {
    id: 4,
    dateAdded: "May 1, 2023",
    propertyName: "Fortune 2 Apartment",
    address: "32, Herbert, Yaba, Lagos",
    unitsLeft: "6",
    propertyType: "Property Purchase",
    status: "Still Selling",
  },
  {
    id: 5,
    dateAdded: "May 1, 2023",
    propertyName: "Fortune 1 Apartment",
    address: "32, Herbert, Yaba, Lagos",
    unitsLeft: "9",
    propertyType: "Co-ownership",
    status: "Still Selling",
  },
  {
    id: 6,
    dateAdded: "May 1, 2023",
    propertyName: "Cambridge Apartment",
    address: "32, Herbert, Yaba, Lagos",
    unitsLeft: "0",
    propertyType: "Co-ownership",
    status: "Sold Out",
  },
  {
    id: 7,
    dateAdded: "May 1, 2023",
    propertyName: "Bedview Apartment",
    address: "32, Herbert, Yaba, Lagos",
    unitsLeft: "0",
    propertyType: "Co-ownership",
    status: "Still Selling",
  },
  {
    id: 8,
    dateAdded: "May 1, 2023",
    propertyName: "Global Suites",
    address: "32, Herbert, Yaba, Lagos",
    unitsLeft: "32",
    propertyType: "Co-ownership",
    status: "Sold Out",
  },
  {
    id: 9,
    dateAdded: "May 1, 2023",
    propertyName: "Bradford Apartment",
    address: "32, Herbert, Yaba, Lagos",
    unitsLeft: "70",
    propertyType: "Property Purchase",
    status: "Still Selling",
  },
  {
    id: 10,
    dateAdded: "May 1, 2023",
    propertyName: "Bradford Suite",
    address: "32, Herbert, Yaba, Lagos",
    unitsLeft: "12",
    propertyType: "Property Purchase",
    status: "Still Selling",
  },
];
