apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: healerkay/lantan-frontend:1
        ports:
        - containerPort: 5173

---        
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  type: LoadBalancer  # Corrected from 'N' to 'NodePort'
  ports:
    - protocol: TCP
      port: 80        # External port for service
      targetPort: 5173 # Port on the container
   # Optional: specify a NodePort, or let Kubernetes assign one automatically
  selector:
    app: frontend


# "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
