name: CI/CD Pipeline to EKS with Docker Hub

on:
  push:
    branches:
      - main        
      - staging 
  pull_request:
    branches:
      - main
      - staging  
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'
      - 'Dockerfile'

jobs:
  build-and-push:
    name: Build Docker Image and Push to Docker Hub
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: healerkay 
      IMAGE_NAME: healerkay/lantan-frontend 
      IMAGE_TAG: ${{ github.sha }} 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}  

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

  deploy-to-eks-staging:
    name: Deploy to EKS Staging
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/staging'

    env:
      AWS_REGION: us-east-1   
      CLUSTER_NAME: mycluster
      DOCKER_IMAGE: Healerkay/lantan-frontend:${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Install kubectl"
        uses: azure/setup-kubectl@v3
        with: 
          version: "v1.19.3"
        id: "install-kubectl"

      - name: "Setup AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: $AWS_REGION
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      - name: "Install Helm"
        uses: azure/setup-helm@v4.2.0
        id: "install-helm"
  
      - name: Deploy to Staging
        run: |
            helm upgrade --install lantan-front lantan-front/ -f lantan-front/values.yaml \
            --set image.tag=${{ github.sha }} \
            --set replicaCount=3

  deploy-to-eks-production:
    name: Deploy to EKS Production
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    env:
      AWS_REGION: us-east-1  
      CLUSTER_NAME: mycluster
      DOCKER_IMAGE: Healerkay/lantan-frontend:${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Install kubectl"
        uses: azure/setup-kubectl@v3
        with: 
          version: "v1.19.3"
        id: "install-kubectl"

      - name: "Setup AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name $CLUSTER_NAME --region us-east-1

      - name: "Install Helm"
        uses: azure/setup-helm@v4.2.0
        id: "install-helm"
  
      - name: Deploy to production
        run: |
            helm upgrade --install lantan-front lantan-front/ -f lantan-front/values.yaml \
            --set image.tag=${{ github.sha }} \
            --set replicaCount=3