name: CI/CD Pipeline to EKS with Docker Hub

on:
  push:
    branches:
      - main        # Deploy to production on main branch
      - staging     # Deploy to staging on staging branch

jobs:
  build-and-push:
    name: Build Docker Image and Push to Docker Hub
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: your-dockerhub-username  # Set your DockerHub username
      IMAGE_NAME: your-dockerhub-username/lantan-frontend # Replace with your DockerHub image name
      IMAGE_TAG: ${{ github.sha }} # Use commit SHA as the image tag

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # You must add your Docker Hub token as a GitHub secret

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

  deploy-to-eks-staging:
    name: Deploy to EKS Staging
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/staging'

    env:
      AWS_REGION: us-west-2   # Set your AWS region
      CLUSTER_NAME: my-staging-cluster
      DOCKER_IMAGE: your-dockerhub-username/lantan-frontend:${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          sudo curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      - name: Deploy to Staging
        run: |
          kubectl set image deployment/frontend-deployment frontend-container=$DOCKER_IMAGE
          kubectl rollout status deployment/frontend-deployment

  deploy-to-eks-production:
    name: Deploy to EKS Production
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    env:
      AWS_REGION: us-west-2   # Set your AWS region
      CLUSTER_NAME: my-production-cluster
      DOCKER_IMAGE: your-dockerhub-username/lantan-frontend:${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          sudo curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      - name: Deploy to Production
        run: |
          kubectl set image deployment/frontend-deployment frontend-container=$DOCKER_IMAGE
          kubectl rollout status deployment/frontend-deployment
